package utils;

import java.util.*;

public class TeamName {  
  // Creates an array list with all the names that we can use to create a team at random.
  public static List<String> Names() {
    return new ArrayList<String>() {{
      add("Abstract Lee Valley Leisure");
      add("Abstract Petticoat Borough");
      add("Abstract Queen's Town");
      add("Assert Brick Hill");
      add("Assert Calthorpe Project United");
      add("Boolean Jubilee Villas");
      add("Boolean Regent's Canal United");
      add("Boolean Russia Dock Albion");
      add("Break Hampstead United");
      add("Break Hoxton Leisure");
      add("Break Priory Hill");
      add("Break Southall Rangers");
      add("Byte Surrey Rovers");
      add("Byte Thames Barrier Rovers");
      add("Case Waterlow College");
      add("Catch Limehouse Basin Ramblers");
      add("Catch Sir John McDougal College");
      add("Catch Tooting Bec Common Reserves");
      add("Catch Wandle Wanderers");
      add("Catch West Ham Albion");
      add("Char McDermott Stanley");
      add("Char Queens Rovers");
      add("Class Blackheath Reserves");
      add("Class Foots Cray Meadows Sporting Club");
      add("Class Hertford Canal City");
      add("Class Railway Hill");
      add("Class Violet F.C.");
      add("Const Streatham Common Rovers");
      add("Const Surrey Docks Stanley");
      add("Const Telegraph Town");
      add("Const Tyburn Leisure");
      add("Continue Chapel Villas");
      add("Continue Mitcham Green");
      add("Continue Romford United");
      add("Continue Teddington Lock United");
      add("Default Harrow Albion");
      add("Default Inverness City");
      add("Default Valence Stanley");
      add("Do Lower Marsh Ramblers");
      add("Do Museum of History Green");
      add("Do Trent Town");
      add("Double Chelsea Physic Rangers");
      add("Double Finsbury F.C.");
      add("Double Mount Wanderers");
      add("Double Pymmes Park");
      add("Double Queen's Wood Park");
      add("Double Ridley Ramblers");
      add("Else Ladbroke Estate Albion");
      add("Else One Tree City");
      add("Else Weavers Field F.C.");
      add("Else Woollett Hall Park");
      add("Enum Hounslow Urban F.C.");
      add("Enum Lamorbey Reserves");
      add("Enum Sayes Court F.C.");
      add("Extends Larkhall Athletic");
      add("Extends Lyle Rangers");
      add("Extends Whitecross College");
      add("Final Broadway Wanderers");
      add("Final Hampstead Heath Town");
      add("Final London Wanderers");
      add("Final Phoenix Rangers");
      add("Final Red Cross Wanderers");
      add("Final Tooting Graveney Common Reserves");
      add("Float Gwendwr City");
      add("Float Mile End Park");
      add("Float Norwood Hill");
      add("Float Peckham Rye Rangers");
      add("Float Vauxhall City Green");
      add("For Hackney City Hill");
      add("For Telegraph Ramblers");
      add("For Tower Rovers");
      add("If Pierhead Lock Rangers");
      add("If Potter's Close Albion");
      add("If Queen's Green");
      add("Implements Furnivall Rovers");
      add("Implements Stepney City Park");
      add("Implements Valentines Town");
      add("Imports Mudchute and Athletic");
      add("Imports Wapping Recreation Ground Borough");
      add("Instance Of Herne Leisure");
      add("Int Bermondsey United");
      add("Int Camden Lock Hill");
      add("Int Grand Union Canal F.C.");
      add("Int Ham House United");
      add("Int Inwood Stanley");
      add("Int King's Stairs Leisure");
      add("Int Primrose United");
      add("Interface Alexandra Stanley");
      add("Interface Crystal Palace Athletic");
      add("Interface Elsinge Green Town");
      add("Interface Portobello Villas");
      add("Long Columbia Rangers");
      add("Long Down Reserves");
      add("Long Newlands Reserves");
      add("Long Victoria Ramblers");
      add("Native Clapham Common Wanderers");
      add("Native Gunnersbury Athletic");
      add("Native Hackney Downs College");
      add("New Coombe Wood House City");
      add("New Danson Leisure");
      add("New Spa City");
      add("Package Brixton Green");
      add("Package Dulwich Town");
      add("Package Kew Rangers");
      add("Package Raphael Sporting Club");
      add("Package Westow Ramblers");
      add("Package Wimbledon Common Ramblers");
      add("Private Kennington Villas");
      add("Private Muswell Park");
      add("Private Queen's Crescent Ramblers");
      add("Private Shooters Rovers");
      add("Protected Battersea Borough");
      add("Protected Camden Canal City");
      add("Protected Camley Natural Wanderers");
      add("Protected Island Reserves");
      add("Public Paddington Park");
      add("Public Putney Common Leisure");
      add("Public Riverwalk Reserves");
      add("Public Vauxhall Villas");
      add("Public Wenlock Basin Athletic");
      add("Return Clissold Wanderers");
      add("Return Deen City City");
      add("Return Kentish Town City Leisure");
      add("Return Ravenscourt F.C.");
      add("Schronized Brockwell Park");
      add("Schronized Camden Sporting Club");
      add("Schronized East Albion");
      add("Schronized Freightliners City F.C.");
      add("Schronized Wandsworth Common Park");
      add("Schronized Watney Borough");
      add("Short Buck Park");
      add("Short Green");
      add("Short Parliament City");
      add("Static Berwick Stanley");
      add("Static Crystal Palace Leisure");
      add("Static Richmond Rovers");
      add("Static Ruskin Leisure");
      add("Static Stables Sporting Club");
      add("Static Sutcliffe Rovers");
      add("Super Duppas F.C.");
      add("Super Horsendon Green");
      add("Super Postman's Albion");
      add("Super Prescott Channel Athletic");
      add("Super Primrose United");
      add("Super Putney Heath Rangers");
      add("Super Walthamstow F.C.");
      add("Super Wandsworth City");
      add("Switch Grosvenor Canal United");
      add("Switch Hammersmith Borough");
      add("Switch Leather Town");
      add("Switch Limehouse Cut Rovers");
      add("Switch Ludgate Athletic");
      add("Switch Myatt's Rangers");
      add("Switch Radnor Athletic");
      add("Switch River Lee Navigation College");
      add("Switch Southwark United");
      add("Switch Syon Albion");
      add("This Deptford Sporting Club");
      add("This Earlham Athletic");
      add("This Forest Hill");
      add("This Gladstone Rangers");
      add("This Mayesbrook Reserves");
      add("This Victoria Tower Hill");
      add("Throw Shoreditch Town");
      add("Throw Spitalfields City Borough");
      add("Throw Springfield Villas");
      add("Throw Sydenham Athletic");
      add("Throw Wembley Town");
      add("Transient Fairfield Rovers");
      add("Transient Lincoln's Inn Park");
      add("Transient Nag's Head Town");
      add("Transient South Norwood Country Hill");
      add("Try Chrisp Green");
      add("Try Hampton Court Stanley");
      add("Try One Tree Sporting Club");
      add("Try Strawberry Albion");
      add("Try Twickenham Rangers");
      add("Void Croydon Canal Borough");
      add("Void Kenwood Athletic");
      add("Volatile London Wetland Ramblers");
      add("Volatile Paradise Park");    
    }};
  }
}